# Generated by Django 6.0.5 on 2026-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_rename_discount_percent_promocode_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое содержание (одно предложение)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
