# Generated by Django 6.0.5 on 2026-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_faq_options_faq_date_added_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='Выполняемые работы / Обязанности'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees_photos/', verbose_name='Фото сотрудника'),
        ),
    ]
