# Generated by Django 6.0.5 on 2026-05-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_employeeprofile_job_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Предлагаемая оплата (BYN)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Описание и требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название вакансии'),
        ),
    ]
