# Generated by Django 6.0.5 on 2026-05-20 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время создания (Локальное)'),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата/Время создания (UTC)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='timezone_name',
            field=models.CharField(default='Europe/Minsk', max_length=50, verbose_name='Таймзона фиксации'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата сделки (для совместимости)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.employeeprofile', verbose_name='Менеджер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Финальная цена ($)'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.property', verbose_name='Недвижимость'),
        ),
    ]
