# Generated by Django 6.0.5 on 2026-05-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_review_created_at_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='Фото объекта'),
        ),
    ]
