# Generated by Django 6.0.5 on 2026-05-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_deal_created_at_local_deal_created_at_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=10, verbose_name='Тип сделки'),
        ),
    ]
