# Generated by Django 6.0.5 on 2026-09-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_property_deal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='partners_logos/', verbose_name='Логотип')),
                ('website_url', models.URLField(verbose_name='Ссылка на сайт компании')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, verbose_name='Текст сертификата'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history_by_years',
            field=models.TextField(blank=True, verbose_name='История по годам'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='Реквизиты компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='company_videos/', verbose_name='Видео о компании (файл)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (YouTube/iframe)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(verbose_name='Информация о компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='EliteEstate', max_length=150, verbose_name='Название компании'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agency.cart', verbose_name='Корзина')),
                ('item_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
            },
        ),
    ]
