# Generated by Django 6.0.5 on 2026-09-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_partner_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название баннера')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение баннера')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка (опционально)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order', 'id'],
            },
        ),
    ]
