# Generated by Django 6.0.5 on 2026-05-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='discount_percent',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='promo_codes',
            field=models.ManyToManyField(blank=True, related_name='clients', to='agency.promocode', verbose_name='Персональные промокоды'),
        ),
    ]
