# Generated by Django 6.0.5 on 2026-05-19 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_article_image_article_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-date_added'], 'verbose_name': 'Вопрос-ответ (FAQ)', 'verbose_name_plural': 'Вопросы-ответы (FAQ)'},
        ),
        migrations.AddField(
            model_name='faq',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ / Определение'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Вопрос / Термин'),
        ),
    ]
